version: "3"
services:
  diet-manager:
    build:
      context: . #docker file location
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev